#! /usr/bin/sh

alias joplin='joplin-desktop'
alias libreoffice='libreoffice --nologo'
alias writer='libreoffice --nologo --writer &!'
alias calc='libreoffice --nologo --calc &!'
alias impress='libreoffice --nologo --impress &!'
alias ee="nvim"
alias bt='bluetoothctl'
alias bgd='bg; disown'
alias tmuxn='direnv exec / tmux new-session'
alias nnn='nnn -e'
alias o='xdg-open'
alias ssh='kitty +kitten ssh'
alias lg='lazygit'
alias pvpn='protonvpn-cli'
alias tmpd='cd $(mktemp -d)'
alias tmuxonly="tmux kill-pane -a -t 1"
alias instagram="brave --profile-directory='Profile 3' --app='https://www.instagram.com' &!"
alias whatsapp="brave --profile-directory='Profile 4' --app='https://web.whatsapp.com' &!"
alias spotify="brave --profile-directory='Profile 5' --app='https://open.spotify.com' &!"

# Common aliases
alias ls='ls --color=tty'
alias l='ls -lFh'     
alias la='ls -lAFh'   
alias lt='ls -ltFh'   
alias ldot='ls -ld .*'
alias zshrc='${=EDITOR} ${ZDOTDIR:-$HOME}/.zshrc'
alias grep='grep --color'
alias rm='rm -iv'
alias cp='cp -iv'
alias mv='mv -iv'

# Arco stuff
alias free="free -mt"
alias merge="xrdb -merge ~/.Xresources"
alias update-fc='sudo fc-cache -fv'
alias mirror="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist"
alias mirrord="sudo reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist"
alias mirrors="sudo reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist"
alias mirrora="sudo reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist"

# Paru aliases
alias prrem='paru -Rnsu'
alias upall='paru -Syu'
