#!/bin/sh

export CALIBRE_USE_DARK_PALETTE=1
export QT_QPA_PLATFORMTHEME=qt5ct

{%@@ if profile == "apex" @@%}
xrandr --output eDP1 --primary --mode 3200x1800
{%@@ endif @@%}
eval "$(gnome-keyring-daemon --start)"
export SSH_AUTH_SOCK
xset s 600
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
dex -a &
