# XDG Dirs
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
for f in $ZDOTDIR/zshenv.d/**/*.zsh(N); do [ -r "$f" ] && source "$f"; done
skip_global_compinit=1
