actions:
  awesome: '[[ -d ~/.config/awesome/lain ]] && git -C ~/.config/awesome/lain pull
    origin master || gh repo clone lcpz/lain ~/.config/awesome/lain; [[ -d ~/.config/awesome/bling
    ]] && git -C ~/.config/awesome/bling pull origin master || gh repo clone BlingCorp/bling
    ~/.config/awesome/bling'
  tmux: '[[ -d ~/.tmux/plugins/tpm ]] && git -C ~/.tmux/plugins/tpm pull origin master
    || (mkdir -p .tmux/plugins && gh repo clone tmux-plugins/tpm ~/.tmux/plugins/tpm)'
  zsh: trash ~/.config/zsh/**/*.zwc
dynvariables:
  home: echo $HOME
config:
  backup: true
  create: true
  dotpath: dotdot
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: true
  showdiff: true
  workdir: ~/.local/share/dotdrop
  instignore:
  - '*/.gitignore'
  cmpignore:
  - '*/.gitignore'
dotfiles:
  d_config_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  d_config_alacritty:
    src: config/alacritty
    dst: ~/.config/alacritty
  d_config_awesome:
    src: config/awesome
    dst: ~/.config/awesome
    actions:
    - awesome
    upignore:
    - lain
    - bling
    cmpignore:
    - lain
    - bling
  d_config_beets:
    src: config/beets
    dst: ~/.config/beets
    upignore:
    - state.pickle
    cmpignore:
    - state.pickle
  d_config_direnv:
    src: config/direnv
    dst: ~/.config/direnv
  d_config_doom:
    src: config/doom
    dst: ~/.config/doom
    upignore:
    - lisp
    - custom.el
    cmpignore:
    - lisp
    - custom.el
  d_config_kitty:
    src: config/kitty
    dst: ~/.config/kitty
  d_config_nnn:
    src: config/nnn
    dst: ~/.config/nnn
  f_config_picom.conf:
    src: config/picom.conf
    dst: ~/.config/picom.conf
  d_config_ripgrep:
    src: config/ripgrep
    dst: ~/.config/ripgrep
  d_config_rofi:
    src: config/rofi
    dst: ~/.config/rofi
  d_config_sxhkd:
    src: config/sxhkd
    dst: ~/.config/sxhkd
  d_config_tilda:
    src: config/tilda
    dst: ~/.config/tilda
    chmod: '700'
  d_config_zsh:
    src: config/zsh
    dst: ~/.config/zsh
    actions:
    - zsh
    ignore_missing_in_dotdrop: true
  f_config_screenkey.json:
    src: config/screenkey.json
    dst: ~/.config/screenkey.json
  f_zshenv:
    src: zshenv
    dst: ~/.zshenv
  f_xprofile:
    src: xprofile
    dst: ~/.xprofile
    chmod: '744'
  f_aliases:
    src: aliases
    dst: ~/.aliases
  d_config_interception:
    src: config/interception
    dst: ~/.config/interception
  f_tmux.conf:
    src: tmux.conf
    dst: ~/.tmux.conf
    actions:
    - tmux
  d_config_git:
    src: config/git
    dst: ~/.config/git
  d_moc:
    src: moc
    dst: ~/.moc
    chmod: '700'
  d_config_mpd:
    src: config/mpd
    dst: ~/.config/mpd
  d_config_ncmpcpp:
    src: config/ncmpcpp
    dst: ~/.config/ncmpcpp
    instignore:
    - .gitignore
  d_config_mopidy:
    src: config/mopidy
    dst: ~/.config/mopidy
  d_config_tridactyl:
    src: config/tridactyl
    dst: ~/.config/tridactyl
profiles:
  sorcery:
    dotfiles:
    - d_config_nvim
    - d_config_awesome
    - d_config_beets
    - d_config_direnv
    - d_config_doom
    - d_config_kitty
    - d_config_nnn
    - f_config_picom.conf
    - d_config_ripgrep
    - d_config_rofi
    - d_config_sxhkd
    - d_config_zsh
    - f_config_screenkey.json
    - f_zshenv
    - f_xprofile
    - f_aliases
    - f_tmux.conf
    - d_config_git
    - d_config_ncmpcpp
        # - d_config_mopidy
    - d_config_tridactyl
  apex:
    dotfiles:
    - d_config_awesome
    - d_config_nvim
    - d_config_doom
    - d_config_kitty
    - f_config_picom.conf
    - d_config_ripgrep
    - d_config_rofi
    - d_config_sxhkd
    - d_config_zsh
    - f_zshenv
    - f_xprofile
    - f_aliases
    - d_config_interception
    - f_tmux.conf
    - d_config_git
    - d_moc
  work:
    dotfiles:
    - d_config_zsh
    - f_zshenv
    - f_aliases
    - d_config_doom
    - d_config_ripgrep
    - d_config_nvim
  localhost:
    dotfiles:
    - d_config_doom
