vim.g.loaded_python_provider = 0
vim.g.loaded_ruby_provider = 0
vim.g.loaded_node_provider = 0
vim.g.loaded_perl_provider = 0
vim.g.loaded_sql_completion = 1 -- $VIMRUNTIME/autoload/sqlcomplete.vim
vim.g.omni_sql_no_default_maps = 1
vim.g.loaded_2html_plugin = 1 -- $VIMRUNTIME/plugin/tohtml.vim
vim.g.loaded_getscript = 1 -- $VIMRUNTIME/autoload/getscript.vim
vim.g.loaded_getscriptPlugin = 1 -- $VIMRUNTIME/plugin/getscriptPlugin.vim
vim.g.loaded_logipat = 1 -- $VIMRUNTIME/plugin/logiPat.vim
vim.g.loaded_logiPat = 1 -- $VIMRUNTIME/plugin/logiPat.vim
vim.g.loaded_netrw = 1 -- $VIMRUNTIME/autoload/netrw.vim
vim.g.loaded_netrwFileHandlers = 1 -- $VIMRUNTIME/autoload/netrwFileHandlers.vim
vim.g.loaded_netrwPlugin = 1 -- $VIMRUNTIME/plugin/netrwPlugin.vim
vim.g.loaded_netrwSettings = 1 -- $VIMRUNTIME/autoload/netrwSettings.vim
vim.g.loaded_rrhelper = 1 -- $VIMRUNTIME/plugin/rrhelper.vim
vim.g.loaded_vimball = 1 -- $VIMRUNTIME/autoload/vimball.vim
vim.g.loaded_vimballPlugin = 1 -- $VIMRUNTIME/plugin/vimballPlugin.vim
