export VISUAL="nvim"
export TERMINAL="kitty"
export BROWSER="firefox"
export FILE="thunar"
export GUIEDITOR="codium"
export SETTINGS="lxqt-config-session"
export LAUNCHER='rofi -modi drun -show drun -show-icons'
export RUNNER='rofi -run-list-command "showaliases" -run-command "/bin/bash -i -c {cmd}" -modi run -show run'
export CALC="galculator"
export LOCKER="xset s activate"
