nmap <silent> gcc <Plug>kommentary_line_default
nmap <silent> gc <Plug>kommentary_motion_default
vmap <silent> gc <Plug>kommentary_visual_default<Esc>
nmap <silent> gcyy <Plug>kommentary_comment_and_yank
nmap <silent> gcy <Plug>kommentary_comment_and_yank_motion
vmap <silent> gcy <Plug>kommentary_comment_and_yank_visual
nmap <silent> gcdd <Plug>kommentary_comment_and_duplicate
nmap <silent> gcd <Plug>kommentary_comment_and_duplicate_motion
vmap <silent> gcd <Plug>kommentary_comment_and_duplicate_visual
