TIMING:
  TAP_MILLISEC: 200
  DOUBLE_TAP_MILLISEC: 0

MAPPINGS:
  - KEY: KEY_CAPSLOCK
    TAP: KEY_ESC
    HOLD: KEY_ESC
  - KEY: KEY_ESC
    TAP: KEY_CAPSLOCK
    HOLD: KEY_CAPSLOCK
  - KEY: KEY_Z
    TAP: KEY_Z
    HOLD: KEY_LEFTCTRL
  - KEY: KEY_SLASH
    TAP: KEY_SLASH
    HOLD: KEY_RIGHTCTRL
