local U = require'snippets.utils'

local html = {
	nbs = [[ &nbsp; ]],
	-- ←,
	left = [[ &#x2190; ]],
	-- →,
	right = [[ &#x2192; ]],
	-- ↑,
	up = [[ &#x2191; ]],
	-- ↓,
	down = [[ &#x2193; ]],
	-- ↩,
	['return'] = [[ &#x21A9; ]],
	-- ⇤,
	backtab = [[ &#x21E4; ]],
	-- ⇥,
	tab = [[ &#x21E5; ]],
	-- ⇧,
	shift = [[ &#x21E7; ]],
	-- ⌃,
	ctrl = [[ &#x2303; ]],
	-- ⌅,
	enter = [[ &#x2305; ]],
	-- ⌘,
	cmd = [[ &#x2318; ]],
	-- ⌥,
	option = [[ &#x2325; ]],
	-- ⌦,
	delete = [[ &#x2326; ]],
	-- ⌫,
	backspace = [[ &#x232B; ]],
	-- ⎋,
	esc = [[ &#x238B; ]],
	-- comment,
	['//'] = [[ <!-- ${1} -->${0} ]],
	attr = [[ ${1:attribute}="${0:property}" ]],
	['attr+'] = [[ ${1:attribute}="${2:property}" attr+ ]],
	['.'] = [[ class="${1}" ]],
	['#'] = [[ id="${1}" ]],
	alt = [[ alt="${1}" ]],
	charset = [[ charset="${1:utf-8}" ]],
	data = [[ data-${1}="${2:$1}" ]],
	['for'] = [[ for="${1}" ]],
	height = [[ height="${1}" ]],
	href = [[ href="${1:#}" ]],
	lang = [[ lang="${1:en}" ]],
	media = [[ media="${1}" ]],
	name = [[ name="${1}" ]],
	rel = [[ rel="${1}" ]],
	scope = [[ scope="${1:row}" ]],
	src = [[ src="${1}" ]],
	title = [[ title="${1}" ]],
	type = [[ type="${1}" ]],
	value = [[ value="${1}" ]],
	width = [[ width="${1}" ]],
	viewport = [[ <meta name="viewport" content="width=device-width, initial-scale=1"> ]],
}

local m = {}

m.get_snippets = function()
	return html
end

return m
